### ISSUE TITLE
/simple/price market cap, 24 hour vol, 24 hour change and last updated

### ISSUE THREAD

**Issue by AnimusXCASH** [man-c/pycoingecko#11]
Hi, 

i have been trying to access the other params as well but do not know how to? Did you implement them at all?

additional/optional params according to the web page

/simple/price
include_market_cap
include_24hr_vol
include 24h_change
include_last_update_at

brg

**Comment by man-c** [comment]
Hi,

All the additional/optional (non-required) arguments can be passed as parameters using the names defined in CoinGecko API doc. There are already some the examples in the readme (README.md) of the library.

Εxample for the **/simple/price** endpoint:

Only required params given:
```python
>>> cg.get_price(ids='bitcoin', vs_currencies='usd')
{'bitcoin': {'usd': 8847.5}}
```

With additional/optional params:
```python
>>> cg.get_price(ids='bitcoin', vs_currencies='usd', include_market_cap='true', include_24hr_vol='true', include_24hr_change='true', include_last_updated_at='true')
{'bitcoin': 
  {'usd': 8836.83,
  'usd_market_cap': 161255769311.96457, 
  'usd_24h_vol': 47478012784.67546, 
  'usd_24h_change': 2.83953864074271, 
  'last_updated_at': 1583162452}
}
```

Best,
Manolis
