### ISSUE TITLE
no pageing is bs

### ISSUE THREAD

**Issue by hivemall** [man-c/pycoingecko#12]
see : https://github.com/man-c/pycoingecko/blob/master/pycoingecko/api.py#L109 
says no paging,
if i request
```
params = {'vs_currency': 'btc',
          'order': 'market_cap_desc',
          # 'per_page': 250,
          # 'page': 1,
          # 'sparkline': 'false'
          }
v = cg.get_coins_markets(**params)

```
results in 100 items , thus paging VERY MUCH REQUIRED.
at least be upfront about it.

**Comment by man-c** [comment]
This may have been left there from previous version of [Coingecko API documentation](https://www.coingecko.com/en/api) (with no pagination required in /coins/markets endpoint, like in /coins/list:
_List all supported coins id, name and symbol (no pagination required)_)
