### ISSUE TITLE
No per_page & page on /exchanges

### ISSUE THREAD

**Issue by evolvex** [man-c/pycoingecko#14]
Hi, thanks for doing this, most useful.

The /exchanges endpoint, according to coingecko defaults to 100 records.

Without the option being available to fetch more and request the 2nd page, it becomes limited as can never get a full list.

Can you change this to include these options?

get_exchanges_list(self, per_page=100, page=1) perhaps? Seems to match with the API documentation?

I could do a pull request if that helps - pretty new to programming so there maybe a reason why this isn't included.

**Comment by man-c** [comment]
Hi,

Done! Just changed `get_exchanges_list()` to accept optional arguments such as _per_page_ and _page_ (578c71ad5d12c73fd60890a35282deb550663416).
For now it is only included in the develop branch (https://github.com/man-c/pycoingecko/tree/develop).

I will merge it with master soon and release a new version, after checking for any other needed changes/updates.

In case you want to use it now, you can manually install the package from source, switching to develop branch:

```bash
git clone https://github.com/man-c/pycoingecko.git
cd pycoingecko
git checkout develop
python3 setup.py install
```

Thanks for notifying!

**Comment by evolvex** [comment]
Excellent stuff. I'll download the branch later. Thanks.

**Comment by man-c** [comment]
@evolvex 
FYI: I just uploaded a newer version (1.3.0), where the wrapper accepts optional arguments for **ALL** the endpoints.
You can install it also by pip (`pip install --upgrade pycoingecko`).

**Comment by evolvex** [comment]
Good stuff, thanks man. Gave it a quick look, looks good! Thanks for updating it :)
