### ISSUE TITLE
Wrong id  Return 

### ISSUE THREAD

**Issue by adityaknegi** [man-c/pycoingecko#15]
co = CoinGeckoAPI()
store =co.get_coins_list()
wrong_id =[(s['id'],i) for i,s in enumerate(store) if "academy token"  in s['id']]

wrong_id

### output 

[('academy token', 203)]

### ALSO tried 

import requests
import json
data= requests.get('https://api.coingecko.com/api/v3/coins/list')
data=json.loads(data.content)
data[203]
{'id': 'academy token', 'name': 'Academy Token', 'symbol': 'acad'}

'id': 'academy token', id is wrong 
the id should be academy-token (https://www.coingecko.com/en/coins/academy-token)

Let me know if anything is Wrong Thank you

**Comment by man-c** [comment]
Hi,

This is **id** of the API.

You can check by the **/coins/list** endpoint: https://api.coingecko.com/api/v3/coins/list 
```
203:
     id: "academy token"
     symbol: "acad"
     name: "Academy Token"
```
and using the **/coins/{id}** endpoint: https://api.coingecko.com/api/v3/coins/academy%20token 
```
{
  "id": "academy token",
  "symbol": "acad",
  "name": "Academy Token",
  "asset_platform_id": "ethereum",
  "block_time_in_minutes": 0,
  "hashing_algorithm": null,
  "categories": [
    "Education"
  ],
...
}
```
Using as an **id** the `academy-token` (https://api.coingecko.com/api/v3/coins/academy-token) the API returns error:

```
{
  "error": "Could not find coin with the given id"
}
```
So, this is just the **id** (`academy token`) that the API uses

For anything else you should contact CoinGecko.

Best
