### ISSUE TITLE
Standardization behind id

### ISSUE THREAD

**Issue by jiamijiang** [man-c/pycoingecko#19]
Is there anyway to just use the 3 letter/4 letter ticker for when searching for an asset instead of having to type out the whole name? And if the name consists of two words, i.e. wrapped-bitcoin or yearn-finance, is it always mandatory to put a hyphen "-" in between the two words?

**Comment by mfiro** [comment]
I guess there is no way and you have to write a function for yourself. You can get the complete list of coins with using: cg.get_coins_list() . And then use string.startswith() method of python to find your desired ticker.

**Comment by man-c** [comment]
The id of the coins (whole name) and the format (e.g. hyphen "-" between words) are defined this way by CoinGecko.
For alternatives, you need to work on your own custom solutions, as @mfiro suggested.
