### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Fede22922** [man-c/pycoingecko#22]
Hi, I'm new on Python programming and i'm going to use pycoingecko. Using the function "cg.get_coin_market_chart_by_id()" when I insert the parameters I don't known what I have to insert in "self".
Can someone help me?

**Comment by man-c** [comment]
Hi,

You don't need to pass anything for 'self'. Just insert the rest parameters.

For example for ```cg.get_coin_market_chart_by_id```:

```python
import pycoingecko
cg = pycoingecko.CoinGeckoAPI()
cg.get_coin_market_chart_by_id(id='bitcoin', vs_currency='eur', days=1)
```

There are more examples in [README](https://github.com/man-c/pycoingecko#examples).

**Comment by Fede22922** [comment]
Thank you very much and sorry for the trivial question

**Comment by man-c** [comment]
No problem!

Best
