### ISSUE TITLE
Support for Apple's arm64 architecture (osx-arm64)

### ISSUE THREAD

**Issue by kartzke** [man-c/pycoingecko#23]
Hi, I'm trying to install `pycoingecko` on a new Apple MacBook with Apple Silicon, but it fails to install via Conda due to no packages matching the architecture. 

Would it be possible to add support for this?

**Comment by man-c** [comment]
Hi! Are trying to install it using pip, `pip install pycoingecko`? You can also install the package from source (see README).

**Comment by kartzke** [comment]
No, sorry about that. I was trying to use `conda`, which kept telling me there was no wheel supporting the architecture, but using pip built the wheel from source successfully. Sorry for the false flag, I'll close the ticket.  🙂
