### ISSUE TITLE
Some Id's don't work.

### ISSUE THREAD

**Issue by NathanRussell22** [man-c/pycoingecko#27]

**Comment by NathanRussell22** [comment]
cg.get_price(ids='Crypto.com Coin', vs_currencies='cad') returns {}

you can see the crypto.com id is valid by calling cg.get_coins_list()

**Comment by man-c** [comment]
Hi,
You are using wrong id. The id for _crypto.com_ is "_crypto-com-chain_".

You can find the ids using cg.get_coins_list() (List with all supported coins id, name and symbol). 
The info for _crypto.com_in the list is:
```
  {
    "id": "crypto-com-chain",
    "symbol": "cro",
    "name": "Crypto.com Coin"
  }
```
