### ISSUE TITLE
Difference number in exchanges__list compared to website

### ISSUE THREAD

**Issue by tmlynowski** [man-c/pycoingecko#3]
Dear author,

I have just installed your libary. When running exchanges_list = cg.get_exchanges_list() in python it returns a list of 235 exchanges. the website in top left says 264 here: https://www.coingecko.com/api#

when running coins_list = cg.get_coins_list() returns 3648 same as the website
so noticed this discrepancy on exchanges
is this an issue that requries investigating?
please let me know
thanks
tom

**Comment by tmlynowski** [comment]
Hi

This is the response I got from coingecko as I wantyed to double check the
endpoint request

"Good to hear from you. The reason why it's showing about 233 in the API is
because the rest have zero volume.
You can see here: https://www.coingecko.com/en/exchanges/
After around 233 or so the volume is $0 and this could be due to several
factors such as exchange API being down or some other integration issues.

--
Bobby Ong
Co-founder, CoinGecko
Kind Regards"

Tomasz Mlynowski (BSc, MSc)

**Comment by man-c** [comment]
Great! Thanks for the update!
