### ISSUE TITLE
get_coins_markets() no sparkline

### ISSUE THREAD

**Issue by trevisanj** [man-c/pycoingecko#35]
```import pycoingecko
cg = pycoingecko.CoinGeckoAPI()

m = cg.get_coins_markets(vs_currency="USD", per_page=1, order="market_cap_desc", page=1, sparkline=True, price_change_percentage="1h,24h,7d,14d,30d,200d,1y")
print(m)
```

You've got to do it as ```sparkline='true'``` otherwise the sparkline does not come

Boolean conversion to a string that CoinGecko can understand would be nice

**Comment by trevisanj** [comment]
I just created a pull request having this.

**Comment by man-c** [comment]
Great! Thanks for contributing.
I was already planning to include this behavior!
