### ISSUE TITLE
Can I get the updated current price every second interval or 0.1 second interval?

### ISSUE THREAD

**Issue by moonsh** [man-c/pycoingecko#37]
Hi, thank you for sharing this great work.

I wonder there is a way to get more fine interval data.

It seems the blow function is calling delayed price and it's not updated every second.
cg.get_price(ids='bitcoin', vs_currencies='usd')

Thank you.

**Comment by man-c** [comment]
Hi,

I don't think so there is such an option for more frequent interval updates for current price.
Maybe, you could also ask CoinGecko if they provide such options through their API.

If you manage to resolve this, or if you find a way to do it, it would be nice to let us know.

Best.
