### ISSUE TITLE
Support for Python native datetime date object for the api mapped to methods

### ISSUE THREAD

**Issue by dxillar** [man-c/pycoingecko#38]
While calling any API (method), instead of matching exact string format of date on the API side, lets support for Python native datetime's date instead.

**Comment by man-c** [comment]
That would be a nice feature, but there seems to be an inconsistency in the date formats of the API. 
For example in `/coins/{id}/history` the **date** is dd-mm-yyyy (eg. 30-12-2017), while in `/events` the **from_date** and **to_date** the request format is yyyy-mm-dd.
I believe it is best to have it as it is. Users can easily work with datetime and if the API changes the format in an endpoint the package would not be required to update.

Cheers

**Comment by cibic89** [comment]
Hi, getting this first value as date for bitcoin 1367193600000, what format is this?

**Comment by man-c** [comment]
Hi!
The 1367193600000 is timestamp in milliseconds (you can check it easily in https://www.epochconverter.com/). Removing the last 3 digits converts it to seconds on unix time, as you already found.

**Comment by cibic89** [comment]
Ευχαριστώ σε παρέα μου, δυνατο το wrapper σου

> Hi!
> The 1367193600000 is timestamp in milliseconds (you can check it easily in https://www.epochconverter.com/). Removing the last 3 digits converts it to seconds on unix time, as you already found.
