### ISSUE TITLE
How to use the "get_coin_market_chart_range_from_contract_address_by_id()" function?

### ISSUE THREAD

**Issue by andrewcaniglia** [man-c/pycoingecko#39]
I'm trying to use the function with this code:

`cg.get_coin_market_chart_range_from_contract_address_by_id(id = 'ethereum', contract_address = '0x514910771af9ca656af840dff83e8264ecf986ca', vs_currency = 'usd', from_timestamp = 1593650267, to_timestamp = 1593650267)`

and it's just giving me this output:

`{'prices': [], 'market_caps': [], 'total_volumes': []}`

I get this no matter what erc-20 token address I use and no matter what I change the timestamps to. What am I doing wrong here?

**Comment by man-c** [comment]
Yes, as I checked the endpoint seems to work fine by giving a small range to the timestamps.

For example:
```python
>>> cg.get_coin_market_chart_range_from_contract_address_by_id('ethereum', '0x514910771af9ca656af840dff83e8264ecf986ca' ,'usd', 1593650267, 1593655000 )
{'prices': [[1593651883020, 4.767133017286734]], 'market_caps': [[1593651883020, 1818501613.1182184]], 'total_volumes': [[1593651883020, 312022091.0165991]]}
```
