### ISSUE TITLE
Updating Get Requests 

### ISSUE THREAD

**Issue by tmlynowski** [man-c/pycoingecko#4]
Dear author,

Excellent library connecting the API

https://www.coingecko.com/api#
I noticed, there are a few GET requests possibly new on libraray (some beta) if wanted to additionally enhance the library functions?

**HEADER simple**
/simple/price
Get the current price of any cryptocurrencies in any other supported currencies that you need.

/simple/supported_vs_currencies
Get list of supported_vs_currencies.

### HEADER coins

/coins/{id}/status_updates
Get status updates for a given coin (beta)

/coins/{id}/contract/{contract_address}
Get coin info from contract address

**HEADER: exchanges (beta)**

/status_updates
List all status_updates with data (description, category, created_at, user, user_title and pin)

**HEADER events**

/events
Get events, paginated by 100

/events/countries
Get list of event countries

/events/types
Get list of events types

**HEADER exchange_rates**

/exchange_rates
Get BTC-to-Currency exchange rates

**Comment by man-c** [comment]
Hello, the new endpoints are included now. Thank you
