### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by countvidal** [man-c/pycoingecko#40]
Hi, there isnt a method for the /coins/categories/list or /coins/categories/

**Comment by man-c** [comment]
Hi! **categories** and **asset_platforms** are new endpoints.
They will be added very soon!

Thanks!

**Comment by man-c** [comment]
The new endpoints (**categories** & **asset_platforms**) have been included in the develop branch. I will merge it with master soon and release a new version.

In case you would like to use them now, you can manually install the package from source, switching to develop branch:
```bash
git clone https://github.com/man-c/pycoingecko.git
cd pycoingecko
git checkout develop
python3 setup.py install
```
