### ISSUE TITLE
Get recently added coins 

### ISSUE THREAD

**Issue by safakyavsan** [man-c/pycoingecko#44]
Hello is there anyway to get the list of latest coins added ? Basicly I want to see if there is any new coin.
https://www.coingecko.com/tr/coins/recently_added
What endpoint should I use ?

**Comment by man-c** [comment]
Hello!
I  haven't seen any endpoint specific for such info, such as latest coins added to CoinGecko.
You could try using the **/coins/list** endpoint: _List all supported coins id, name and symbol (no pagination required)_ (`cg.get_coins_list()`) and save locally the list. Then every time you need to check for new coins, you could compared the saved list with a newer instance of the list with all supported coins.
Best
