### ISSUE TITLE
How to get crypto pair prices (e.g. BTC/ETH)?

### ISSUE THREAD

**Issue by lsverso** [man-c/pycoingecko#56]
If I extract the price of BTC, for example, I can only specify fiat currencies as quote currencies: BTC/[fiat].

Is there an easy way to extract BTC/ETH, ETH/AVAX or any other crypto/crypto pair?

**Comment by nejcb1** [comment]
Get BTC/USD, ETH/USD, AVAX/USD prices from coinapi, then recalculate it on your own. 

Makes sense?

**Comment by lsverso** [comment]
Yep, did it and it worked. Thanks!
