### ISSUE TITLE
New coingecko Python wrapper

### ISSUE THREAD

**Issue by nickatnight** [man-c/pycoingecko#91]
Hi guys, this project seems to be dead (with the last commit over two years ago), and doesn't seem very active. I've created a new fork that supports all the current api endpoints. Project can be found here https://github.com/nickatnight/python-coingecko

**Comment by man-c** [comment]
Hello! pycoingecko release v3.2.0 is enriched with the API's new endpoints, and also supports both **Public API** and **Pro API** with their corresponding API keys (public can used with or without any demo api key)!
Thanks
